# The version of night-config Forge packages still has this bug:
# https://github.com/TheElectronWill/night-config/issues/96
# So we use int codes. aa.

[petra_the_kat]
# colorizer = [0xebad1c, 0xc7c7bd, 0x7c2e94, 0x2e060f]
colorizer = [15445276, 13092797, 8137012, 3016207]

[Hudeler]
#colorizer = [0x825ec2]
colorizer = [8543938]

[AmyMiyalee]
#colorizer = [0xb992ff]
colorizer = [12161791]

[Alwinfy]
#colorizer = [0x3327e3]
colorizer = [3352547]

[Noobulus]
#colorizer = [0x92a1ff, 0x6b7fff]
colorizer = [9609727, 7045119]

[Dev]
# 0xff0000 0x00ff00 0x0000ff
# For testing purposes
colorizer = [16711680, 65280, 255]
