modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"

issueTrackerURL = "https://github.com/gamma-delta/HexMod/issues"

[[mods]]
modId = "hex"
version = "${file.jarVersion}"
displayName = "Hex"
displayURL = "https://github.com/gamma-delta/HexMod"
logoFile = "examplemod.png"
credits = '''
- Alwinfy for visual effects help
- Kra3tor for sound effects
'''
authors = "petrak@ (aka gamma-delta)"
description = '''
Cast complex spells by drawing patterns in the air!
'''

[[dependencies.hex]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hex]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
