modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com/gamma-delta/HexMod/issues"

[[mods]]
modId = "hexcasting"
version = "${file.jarVersion}"
displayName = "Hex"
displayURL = "https://github.com/gamma-delta/HexMod"
logoFile = "logo.png"
credits = "Alwinfy for visual effects and proofreading; Kra3tor for sound effects"
authors = "petrak@ (aka gamma-delta)"
description = "Cast powerful Hexes on the fly by drawing patterns with a staff."

[[dependencies.hex]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hex]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hex]]
modId = "patchouli"
mandatory = true
versionRange = "[1.18.1-65-SNAPSHOT,)"
ordering = "NONE"
side = "BOTH"
